# Generated by Django 5.0.6 on 2026-06-07 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='properties.property'),
        ),
        migrations.AddField(
            model_name='leadpurchase',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_purchases', to='brokers.brokerprofile'),
        ),
        migrations.AddField(
            model_name='leadpurchase',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_purchases', to='properties.property'),
        ),
        migrations.AddField(
            model_name='listingpromotion',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='brokers.brokerprofile'),
        ),
        migrations.AddField(
            model_name='listingpromotion',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='properties.property'),
        ),
    ]
