# Generated by Django 5.0.6 on 2026-06-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipropertysuggestion',
            name='visited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
